<?php

use Aligent\AsyncEvents\Block\Adminhtml\Trace\Tab\View\Info;
use Magento\Framework\Escaper;

/**
 * @var Info $block
 * @var Escaper $escaper
 */

?>

<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-information">
            <div class="admin__page-section-item-title">
                <span class="title">Async Event Delivery Information</span>
            </div>

            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-information-table">
                    <tbody>
                    <?= $block->getChildHtml() ?>
                    <tr class="">
                        <th><?= 'uuid' ?></th>
                        <td><?= $escaper->escapeHtml($block->getUuid()) ?></td>
                    </tr>
                    <tr>
                        <th style="font-weight: bold"><?= 'Status' ?></th>
                        <td style="font-weight: bold"><?= $escaper->escapeHtml($block->getStatus()) ?></td>
                    </tr>
                    <tr>
                        <th><?= 'First attempt time' ?></th>
                        <td><?= $escaper->escapeHtml($block->getFirstAttempt()) ?></td>
                    </tr>
                    <tr>
                        <th><?= 'Last attempt time' ?></th>
                        <td><?= $escaper->escapeHtml($block->getLastAttempt()) ?></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="admin__page-section-item order-account-information">
            <div class="admin__page-section-item-title">
                <span class="title">Subscription Information</span>
            </div>

            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-account-information-table">
                    <tr>
                        <th>Asynchronous Event Name</th>
                        <td>
                            <?= $escaper->escapeHtml($block->getAsynchronousEventName()) ?>
                        </td>
                    </tr>
                    <tr>
                        <th>Current Status</th>
                        <td>
                            <?= $escaper->escapeHtml($block->getCurrentStatus()) ?>
                        </td>
                    </tr>
                    <tr>
                        <th>Recipient</th>
                        <td>
                            <?= $escaper->escapeHtml($block->getRecipient()) ?>
                        </td>
                    </tr>
                    <tr>
                        <th>Subscribed At</th>
                        <td>
                            <?= $escaper->escapeHtml($block->getSubscribedAt()) ?>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</section>

<div class="fieldset-wrapper">
    <div class="fieldset-wrapper-title">
        <span class="title"><?= 'Traces' ?></span>
    </div>
    <div class="admin__table-wrapper">
        <table class="admin__table-primary" style="table-layout: fixed;">
            <thead>
            <tr>
                <th><?= $escaper->escapeHtml(__('Log Id')) ?></th>
                <th><?= $escaper->escapeHtml(__('Delivery Time')) ?></th>
                <th><?= $escaper->escapeHtml(__('Response')) ?></th>
                <th><?= $escaper->escapeHtml(__('Status')) ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($block->getLogs() as $item): ?>
                <tr>
                    <td>
                        <?= $escaper->escapeHtml($item['log_id']) ?>
                    </td>
                    <td>
                        <?= $escaper->escapeHtml($item['created']) ?>
                    </td>
                    <td style="word-wrap: break-word;">
                        <?= $escaper->escapeHtml($item['response_data']) ?>
                    </td>
                    <td class="col-severity">
                        <?= $item['success'] ?
                            '<span class="grid-severity-notice"><span>Success</span></span>' :
                            '<span class="grid-severity-critical"><span>Failed</span></span>' ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

